import { GetStaticProps, NextPage } from 'next';
import Head from 'next/head'
import Image from 'next/image';
import Link from 'next/link';
import imageLoader from '../imageLoader';
import { PokemonListProps, PokemonNameUrl } from '../types';

const Home: NextPage<{pokemons: PokemonNameUrl[]}> = ({ pokemons }) => {
  return (
    <>
      <Head>
        <title>Next Rookie</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container mx-auto">
        <h1 
          className="text-3xl font-bold"
        >
          Hello world!
        </h1>
        <div className="grid grid-cols-4 gap-4">
          {pokemons.map((pokemon) => (
            <div key={pokemon.url}>
              <Link href={`/pokemons/${pokemon.name}`}>
                <p>{pokemon.name}</p>
              </Link>
              <Image
                loader={imageLoader}
                unoptimized
                alt={pokemon.name}
                src={`https://img.pokemondb.net/artwork/large/${pokemon.name}.jpg`}
                width={200}
                height={150}
              />
            </div>
          ))}
        </div>
      </main>
    </>
  )
}

export const getStaticProps: GetStaticProps = async (context) => {
  const res = await fetch('https://pokeapi.co/api/v2/pokemon?limit=20&offset=0');
  const { results }:PokemonListProps = await res.json();
  return {
    props: {
      pokemons: results,
    }
  }
}

export default Home;
